### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nanotamarindo** [Torr7s/beach-forecast-api#1]
hi, I will love to try this script
but I got this error

{"code":404,"message":"not found","error":"Not Found"}

could you please let me know what to do
thank you very much
Mariano

**Comment by matheustrres** [comment]
Hello, @nanotamarindo!

Well, this project has an integrated front-end projects, which was given to me to use with the application. There's a few months since the last time I openned this project, but as far as I've noticed, you will have to go into the server folder and run the `yarn start` command like that `NODE_OPTIONS=--openssl-legacy-provider yarn start` to get the front-end to start correctly, otherwise it will throw an error.

After that, you need to define the client settings in the `api/config/default.json` file, such as the MongoDb url connection, then you will be able to start the api with the `yarn start` command.

Maybe I will mark this repository as deprecated...
